[id="distribution"]
= Distribution of content in RHEL 9

== Installation
Red Hat Enterprise Linux 9 is installed using ISO images. Two types of ISO image are available for the AMD64, Intel 64-bit, 64-bit ARM, IBM Power Systems, and IBM{nbsp}Z architectures:

* Installation ISO: A full installation image that contains the BaseOS and AppStream repositories and allows you to complete the installation without additional repositories. On the link:https://access.redhat.com/downloads/[Product Downloads] page, the `Installation ISO` is referred to as `Binary DVD`.
+
[NOTE]
====

The Installation ISO image is in multiple GB size, and as a result, it might not fit on optical media formats. A USB key or USB hard drive is recommended when using the Installation ISO image to create bootable installation media. You can also use the Image Builder tool to create customized RHEL images. For more information about Image Builder, see the https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/composing_a_customized_rhel_system_image/index/[_Composing a customized RHEL system image_] document.

====

* Boot ISO: A minimal boot ISO image that is used to boot into the installation program. This option requires access to the BaseOS and AppStream repositories to install software packages. The repositories are part of the Installation ISO image. You can also register to Red Hat CDN or Satellite during the installation to use the latest BaseOS and AppStream content from Red Hat CDN or Satellite.

See the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/performing_a_standard_rhel_9_installation/index[Performing a standard RHEL 9 installation] document for instructions on downloading ISO images, creating installation media, and completing a RHEL installation. For automated Kickstart installations and other advanced topics, see the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/performing_an_advanced_rhel_9_installation/[Performing an advanced RHEL 9 installation] document.

== Repositories
//draft: https://docs.google.com/document/d/1pyMhKEkc--ieaJUkg6bL8Z08Gv1jFkDPy3FaCDP7Xhc/edit#heading=h.mhq9qqyi2dt

Red Hat Enterprise Linux 9 is distributed through two main repositories:

* BaseOS
* AppStream

Both repositories are required for a basic RHEL installation, and are available with all RHEL subscriptions.

Content in the BaseOS repository is intended to provide the core set of the underlying OS functionality that provides the foundation for all installations. This content is available in the RPM format and is subject to support terms similar to those in previous releases of RHEL. For more information, see the link:https://access.redhat.com/node/490973[Scope of Coverage Details] document.

Content in the AppStream repository includes additional user-space applications, runtime languages, and databases in support of the varied workloads and use cases.

In addition, the CodeReady Linux Builder repository is available with all RHEL subscriptions. It provides additional packages for use by developers. Packages included in the CodeReady Linux Builder repository are unsupported.

For more information about RHEL 9 repositories and the packages they provide, see the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/package_manifest/index[Package manifest].



== Application Streams
//draft: https://docs.google.com/document/d/1pyMhKEkc--ieaJUkg6bL8Z08Gv1jFkDPy3FaCDP7Xhc/edit#heading=h.3f9lrjuf0gbb
Multiple versions of user-space components are delivered as Application Streams and updated more frequently than the core operating system packages. This provides greater flexibility to customize RHEL without impacting the underlying stability of the platform or specific deployments.

Application Streams are available in the familiar RPM format, as an extension to the RPM format called modules, as Software Collections, or as Flatpaks.

Each Application Stream component has a given life cycle, either the same as RHEL 9 or shorter. For RHEL life cycle information, see link:https://access.redhat.com/support/policy/updates/errata[Red Hat Enterprise Linux Life Cycle].

RHEL 9 improves the Application Streams experience by providing initial Application Stream versions that can be installed as RPM packages using the traditional `dnf install` command.

NOTE: Certain initial Application Streams in the RPM format have a shorter life cycle than Red Hat Enterprise Linux 9.

Some additional Application Stream versions will be distributed as modules with a shorter life cycle in future minor RHEL 9 releases. Modules are collections of packages representing a logical unit: an application, a language stack, a database, or a set of tools. These packages are built, tested, and released together.

Always determine what version of an Application Stream you want to install and make sure to review the link:https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle[Red Hat Enterprise Linux Application Stream Lifecycle] first.

//TODO revive in 9.1
//Detailed module commands are described in the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_software_with_the_dnf_tool[Managing software with the DNF tool] document.

//Commented out - unimportant for 9.0: Module streams represent versions of the Application Stream components. Only one module stream can be installed on the system. Different versions can be used in separate containers.

Content that needs rapid updating, such as alternate compilers and container tools, is available in rolling streams that will not provide alternative versions in parallel. Rolling streams may be packaged as RPMs or modules.

For information about Application Streams available in RHEL 9 and their application compatibility level, see the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/package_manifest/index[Package manifest]. Application compatibility levels are explained in the link:https://access.redhat.com/articles/rhel9-abi-compatibility[Red Hat Enterprise Linux 9: Application Compatibility Guide] document.


[id="package_management_with_yum_dnf"]
== Package management with YUM/DNF

In Red Hat Enterprise Linux 9, software installation is ensured by *DNF*. Red Hat continues to support the usage of the `yum` term for consistency with previous major versions of RHEL. If you type `dnf` instead of `yum`, the command works as expected because both are aliases for compatibility.

Although RHEL 8 and RHEL 9 are based on *DNF*, they are compatible with *YUM* used in RHEL 7.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_software_with_the_dnf_tool[Managing software with the DNF tool].
